language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "a+SvgQoeTUztBHpF04zhSjxldu9vh7AXYdjEXW3K7o9J+ak5z/7tUbbFQX2a/4HlaDlyjSARIIKD+oJBvHFze7gvYgcVNYyhItCs+OQGxCKlQ28KahN0cOBmm/qm9yoZsXpyU+GzXA/E95d0cD3MPUWUYvSDLbnsuSVuwgbiQd8="

addons:
  coverity_scan:
    project:
      name: "konradrenner/stammdaten"
      description: "Your project description here"
    notification_email: koni.renner@gmail.com
    build_command_prepend:
    build_command:
    branch_pattern:
