language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Ea//7vp6Y8+wD2+O7HkPuvCFBBkVqPJ028cHwN4ykpOw3ZVBf4q4nP/sowOPitslxWSMra3QR6yPxJEqI42clDUaXJ//Fm6+04OkarFmo/SgIhMr0wGgYQLlT/3C8N1OcBSfbokMXVhZXnJckv0JBv27kSG3XV2vA/GUwq8ous4="

addons:
  coverity_scan:
    project:
      name: "konradrenner/KoreMenuRI"
      description: "Your project description here"
    notification_email: koni.renner@gmail.com
    build_command_prepend:
    build_command:
    branch_pattern:
